### ISSUE TITLE
Question: how to use this?

### ISSUE THREAD

**Issue by hissssst** [divnix/quick-nix-registry#3]
I have flakes setup, and when I just add this like
```nix
inputs.quick-nix-registry.url = "github:divnix/quick-nix-registry";
```
rebuild fails.

So how to use this?

**Comment by nrdxp** [comment]
So you actually have to import the module that is exported here into your configuration and then set whichever options you'd like. I'll see if I can find some time later to add a short example in the README.md.

Just setting the input as you show above doesn't do anything (except pull the repo and cache it in the nix/store), so it wouldn't cause your rebuild to fail. That must be caused by something else in your config.

**Comment by nrdxp** [comment]
@hissssst, the README should now contain the information you need :+1:
